### PR TITLE
Add ability to play the CSD file in the currently-active editor windo…

### PR DESCRIPTION
**Pull request by forrcaho**
…w from within VSCode

I'm taking some of the lessons that I learned implementing the vscode plugin for ChucK and applying them here. This PR implements a command to play the CSD file in the currently active editor window.

I bumped the version number to 0.2.0 since it's adding a feature.

I know this is a big change; please let me know if you have any questions. I can certainly change the coding style more to your liking if there's a way you'd rather organize it.

### CODE REVIEW

**Comment by stekyne** [comment]
That's great stuff, thanks for the contribution. Coding style looks fine to me.

**Comment by forrcaho** [comment]
I just realized i forgot one of the configuration settings. I'll have another commit for this PR coming shortly -- please hold off on merging until I get that in.

**Comment by rorywalsh** [comment]
This is really cool Forest. I look forward to trying it out ;)

**Comment by forrcaho** [comment]
OK, I made that second commit. This should be good to go.

**Comment by kunstmusik** [comment]
NM, I think the debug extension mode is throwing me off, I see the changes for Changelog and README.

**Comment by kunstmusik** [comment]
Version 0.2.0 published to Marketplace, thanks again @forrcaho .

**Comment by forrcaho** [comment]
> One issue is that if you call the start command multiple times, it will not stop the previous run.

That could be construed as a feature.

It does sound like we probably need a way to kill any running processes. I think perhaps Ctrl+C when the focus is on the Csound output window would be intuitive, or maybe esc. I'll see what I can come up with.

**Comment by rorywalsh** [comment]
I think we definitely need some way of stopping a .csd file too. Or am I missing that? Killing vscode doesn't kill the process.

**Pull request merged**
